/**
 * Make an assertion that `error` is an `Error`.
 * If not then an error will be thrown.
 * An error class and a string that should be included in the
 * error message can also be asserted.
 *
 * @example
 * ```ts
 * import { assertIsError } from "@std/assert/assert-is-error";
 *
 * assertIsError(null); // Throws
 * assertIsError(new RangeError("Out of range")); // Doesn't throw
 * assertIsError(new RangeError("Out of range"), SyntaxError); // Throws
 * assertIsError(new RangeError("Out of range"), SyntaxError, "Out of range"); // Doesn't throw
 * assertIsError(new RangeError("Out of range"), SyntaxError, "Within range"); // Throws
 * ```
 */ export declare function assertIsError<E extends Error = Error>(error: unknown, ErrorClass?: new(...args: any[]) => E, msgMatches?: string | RegExp, msg?: string): asserts error is E;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImFzc2VydF9pc19lcnJvci50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFLQTs7Ozs7Ozs7Ozs7Ozs7OztDQWdCQyxHQUNELE9BQU8saUJBQVMsY0FBYyxVQUFVLFFBQVEsT0FDOUMsT0FBTyxPQUFPLEVBRWQsaUJBQWtCLEdBQUcsTUFBTSxHQUFHLE9BQU8sQ0FBQyxFQUN0QyxhQUFhLE1BQU0sR0FBRyxNQUFNLEVBQzVCLE1BQU0sTUFBTSxXQUNILFNBQVMifQ==